"use client";
import { useCallback,useEffect,useState } from 'react';
import {supabase} from '@/lib/supabase/browser';
type FileRow={name:string;created_at:string|null;metadata?:{size?:number}|null};
export default function TaskAttachments({taskId,canUpload}:{taskId:string;canUpload:boolean}){
 const [files,setFiles]=useState<FileRow[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [offset,setOffset]=useState(0);const [more,setMore]=useState(false);
 const load=useCallback(async (start=0)=>{if(!supabase)return;const {data,error}=await supabase.storage.from('task-attachments').list(taskId,{limit:50,offset:start,sortBy:{column:'created_at',order:'desc'}});if(error){setError(error.message);return;}setError('');setFiles(prev=>start?[...prev,...(data||[])]:data||[]);setOffset(start+50);setMore(data?.length===50);},[taskId]);
 // Storage request resolves asynchronously before any state updates.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void load();},[load]);
 const name=(value:string)=>value.replace(/^[a-f0-9-]{36}_/,'');
 return <details className="my-3 rounded-lg border border-slate-200 bg-white p-3"><summary className="cursor-pointer text-sm font-semibold">Attachments ({files.length}{more?'+':''})</summary><div className="mt-3 space-y-3">{canUpload&&<label className="block text-xs text-slate-500">Add screenshot or document · maximum 10 MB<input aria-label="Upload task attachment" disabled={busy} type="file" accept=".png,.jpg,.jpeg,.webp,.pdf,.txt,.csv,.docx,.xlsx" className="mt-2 block w-full text-xs" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file||!supabase)return;if(file.size>10485760){setError('Choose a file smaller than 10 MB.');return;}setBusy(true);setError('');try{const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_').slice(-150);const {error}=await supabase.storage.from('task-attachments').upload(`${taskId}/${crypto.randomUUID()}_${safe}`,file,{upsert:false});if(error)throw error;await load();}catch(e){setError(e instanceof Error?e.message:'Upload failed.');}finally{setBusy(false);}}}/></label>}{error&&<p role="alert" className="text-xs text-orange-500">{error}</p>}{busy&&<p role="status" className="text-xs">Uploading…</p>}<ul className="space-y-2">{files.map(file=><li key={file.name}><button className="break-all text-left text-sm text-indigo-600" onClick={async()=>{if(!supabase)return;const {data,error}=await supabase.storage.from('task-attachments').createSignedUrl(`${taskId}/${file.name}`,60,{download:true});if(error){setError(error.message);return;}const link=document.createElement('a');link.href=data.signedUrl;link.rel='noopener noreferrer';link.click();}}>{name(file.name)}</button><p className="text-xs text-slate-500">{Math.ceil((file.metadata?.size||0)/1024)} KB · {new Date(file.created_at||0).toLocaleDateString()}</p></li>)}</ul>{!files.length&&!error&&<p className="text-xs text-slate-500">No attachments yet.</p>}{more&&<button className="text-sm text-indigo-600" onClick={()=>load(offset)}>Load more files</button>}<button className="text-xs text-slate-500" onClick={()=>load()}>Refresh files</button></div></details>;
}
